---
services:
  runtime-74:
    image: ghcr.io/sitepilot/runtime:7.4
    build:
      context: .
      args:
        BUILD_PHP_VERSION: "7.4"
    ports:
      - 1022:22
      - 1080:80
      - 1443:443
    environment:
      RUNTIME_USER_ID: 1002
      RUNTIME_USER_NAME: test-user
      RUNTIME_USER_PASSWORD: "$$2y$$10$$MJwRvRbh70kJNrRWp2FzLeF4CJNG4a1tqyggtSeDvcmd4nfNXV5K." # secret
    volumes:
      - ./public:/home/runtime/public
      - ./config.yml:/opt/runtime/config.yml

  runtime-80:
    image: ghcr.io/sitepilot/runtime:8.0
    build:
      context: .
      args:
        BUILD_PHP_VERSION: "8.0"
    ports:
      - 2022:22
      - 2080:80
      - 2443:443
    environment:
      RUNTIME_USER_ID: 1002
      RUNTIME_USER_NAME: test-site
      RUNTIME_USER_PASSWORD: "$$2y$$10$$MJwRvRbh70kJNrRWp2FzLeF4CJNG4a1tqyggtSeDvcmd4nfNXV5K." # secret
    volumes:
      - ./public:/home/runtime/public
      - ./config.yml:/opt/runtime/config.yml
