---
services:
  runtime-74:
    image: ghcr.io/sitepilot/runtime:7.4
    build:
      context: .
      args:
        PHP_VERSION: 74
        PHP_DOT_VERSION: 7.4
    environment:
      RUNTIME_USER_NAME: test-user
      RUNTIME_USER_PASSWORD: "indainda"

  runtime-80:
    image: ghcr.io/sitepilot/runtime:8.0
    build:
      context: .
      args:
        PHP_VERSION: 80
        PHP_DOT_VERSION: 8.0
    environment:
      RUNTIME_USER_NAME: test-user
      RUNTIME_USER_PASSWORD: "indainda"
