---
name: build-operator

on:
  push:
    paths:
      - "operator/**"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push runtime 8.0
        run: |
          cd ./operator
          docker compose build operator
          docker compose run operator
